### ISSUE TITLE
Vorhandene Rollen analysieren und den Desires zuordnen

### ISSUE THREAD

**Issue by phil-32** [h1Modeling/ss22_fp_mapc_gruppe3#43]
Bei unbekannten Rollen müssen diese anhand ihrer Eigenschaften analysiert werden. Die jeweils für ein Desire am besten geeignete Rolle muss diesem zugeordnet werden.

**Comment by h1Modeling** [comment]
Benötigte Rollen werden mittels ActionDesire geholt
