### ISSUE TITLE
Günstige Richtung für Exploration vom Navi zurückbekommen

### ISSUE THREAD

**Issue by phil-32** [h1Modeling/ss22_fp_mapc_gruppe3#48]
Navi sollte die Richtung in der unbekannte Zellen liegen, bzw. Zellen die lange nicht besucht wurden, zurückgeben um die Implementierung der Explorer Desires zu erleichtern.

**Comment by h1Modeling** [comment]
Wurde mit der Methode getDirectionToNearestUndiscoveredPoint in der Klasse Navi realisiert
