### ISSUE TITLE
ReachableDispensers verlieren Einträge

### ISSUE THREAD

**Issue by melinda5** [h1Modeling/ss22_fp_mapc_gruppe3#66]
Wenn ein Agent neben einem Dispenser steht, verschwindet diese Zelle aus den ReachableDispensers.

Wenn ein Block auf einem Dispenser erscheint, oder ein Agent auf einem Dispenser steht. Dann verschwindet der ganze Dispenser, also alle vier ReachableDispenser-Zellen dieses Dispensers.

**Comment by h1Modeling** [comment]
Dispenser haben in der Map Priorität vor Blöcken
